# This is a basic workflow to help you get started with Actions

name: run_job_2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job 
  run_thingy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        apikey: ${{ secrets.APIKEY}}
        apisecretkey: ${{ secrets.APISECRETKEY}}
        access_token: ${{ secrets.ACCESS_TOKEN}}
        access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET}}
        RENV_PATHS_ROOT: ~/.local/share/renv
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
      
      - name: Cache packages
        uses: actions/cache@v1
        with:
           path: ${{ env.RENV_PATHS_ROOT }}
           key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
           restore-keys: |-
              ${{ runner.os }}-renv-
      
      - name: Restore packages
        run: |-
            Rscript 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
            renv::restore()'    

      - name: run-script
        run: |-
           Rscript run_job.R
 
