on:
  schedule:
    - cron: '0 9 * * *'
name: run-job

jobs:
  run-job:
    runs-on: ubuntu-18.04
    env:
        apikey: ${{ secrets.APIKEY}}
        apisecretkey: ${{ secrets.APISECRETKEY}}
        access_token: ${{ secrets.ACCESS_TOKEN}}
        access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET}}
        RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
      with:
       r-version: 4.0.2
    - name: Cache packages
      uses: actions/cache@v1
      with:
         path: ${{ env.RENV_PATHS_ROOT }}
         key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
         restore-keys: |-
            ${{ runner.os }}-renv-
      - name: Restore packages
        shell: Rscript {0}
        run: |-
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
     - name: run-script
       run: |-
         Rscript run_job.R
